"""
=========================================================
PROJECT FALCON
Swing Fibonacci Engine
Version : 3.0 (Frozen)
=========================================================

Calculates Fibonacci retracement levels from the latest
validated swing impulse generated by Swing Engine V3.1.

Responsibilities
----------------
- Validate inputs
- Detect latest impulse
- Calculate Fibonacci retracements
- Calculate Golden Zone
- Validate pullback
- Return SwingFibonacci

This engine performs NO strategy logic,
NO confluence,
NO confidence scoring,
NO trade execution.
=========================================================
"""

from __future__ import annotations

from typing import Optional

import pandas as pd

from models.enums import (
    FibonacciDirection,
    SwingType,
    Strength,
)

from models.swing_fibonacci import SwingFibonacci


class SwingFibonacciEngine:
    """
    Swing Fibonacci Engine.
    """

    MIN_IMPULSE_CANDLES = 8

    REQUIRED_PRICE_COLUMNS = {
        "Open",
        "High",
        "Low",
        "Close",
    }

    REQUIRED_SWING_COLUMNS = {
        "Index",
        "Datetime",
        "Price",
        "Type",
        "Classification",
        "Strength",
    }

    # =====================================================
    # Public API
    # =====================================================

    def calculate(
        self,
        df: pd.DataFrame,
        swings: pd.DataFrame,
    ) -> Optional[SwingFibonacci]:

        if df is None or df.empty:
            return None

        if swings is None or swings.empty:
            return None

        if len(swings) < 2:
            return None

        self._validate_inputs(
            df,
            swings,
        )

        impulse = self._find_latest_impulse(
            swings,
        )

        if impulse is None:
            return None

        levels = self._calculate_levels(
            swing_low=impulse["low"],
            swing_high=impulse["high"],
            direction=impulse["direction"],
        )

        pullback_valid = self._validate_pullback(
            df=df,
            impulse=impulse,
            levels=levels,
        )

        return self._build_result(
            impulse,
            levels,
            pullback_valid,
        )

    # =====================================================
    # Validation
    # =====================================================

    def _validate_inputs(
        self,
        df: pd.DataFrame,
        swings: pd.DataFrame,
    ) -> None:

        missing_price = (
            self.REQUIRED_PRICE_COLUMNS
            - set(df.columns)
        )

        if missing_price:
            raise ValueError(
                f"Missing OHLC columns: {missing_price}"
            )

        missing_swings = (
            self.REQUIRED_SWING_COLUMNS
            - set(swings.columns)
        )

        if missing_swings:
            raise ValueError(
                f"Missing Swing columns: {missing_swings}"
            )

    # =====================================================
    # Latest Impulse
    # =====================================================

    def _find_latest_impulse(
        self,
        swings: pd.DataFrame,
    ) -> Optional[dict]:

        for i in range(
            len(swings) - 1,
            0,
            -1,
        ):

            current = swings.iloc[i]
            previous = swings.iloc[i - 1]

            if not self._validate_impulse(
                previous,
                current,
            ):
                continue

            previous_type = SwingType(
                str(previous["Type"]).upper()
            )

            current_type = SwingType(
                str(current["Type"]).upper()
            )

            if (
                previous_type == SwingType.LOW
                and current_type == SwingType.HIGH
            ):

                return {
                    "direction": FibonacciDirection.BULLISH,
                    "low": float(previous["Price"]),
                    "high": float(current["Price"]),
                    "start_index": int(previous["Index"]),
                    "end_index": int(current["Index"]),
                    "start_time": previous["Datetime"],
                    "end_time": current["Datetime"],
                    "classification": (
                        previous["Classification"],
                        current["Classification"],
                    ),
                }

            if (
                previous_type == SwingType.HIGH
                and current_type == SwingType.LOW
            ):

                return {
                    "direction": FibonacciDirection.BEARISH,
                    "high": float(previous["Price"]),
                    "low": float(current["Price"]),
                    "start_index": int(previous["Index"]),
                    "end_index": int(current["Index"]),
                    "start_time": previous["Datetime"],
                    "end_time": current["Datetime"],
                    "classification": (
                        previous["Classification"],
                        current["Classification"],
                    ),
                }

        return None
        # =====================================================
    # Impulse Validation
    # =====================================================

    def _validate_impulse(
        self,
        previous,
        current,
    ) -> bool:
        """
        Validate whether two consecutive swings form a
        tradable impulse.
        """

        candle_distance = (
            int(current["Index"])
            - int(previous["Index"])
        )

        if candle_distance < self.MIN_IMPULSE_CANDLES:
            return False

        if float(previous["Price"]) == float(current["Price"]):
            return False

        previous_strength = Strength(
            str(previous["Strength"]).upper()
        )

        current_strength = Strength(
            str(current["Strength"]).upper()
        )

        if previous_strength == Strength.WEAK:
            return False

        if current_strength == Strength.WEAK:
            return False

        previous_type = SwingType(
            str(previous["Type"]).upper()
        )

        current_type = SwingType(
            str(current["Type"]).upper()
        )

        bullish = (
            previous_type == SwingType.LOW
            and current_type == SwingType.HIGH
        )

        bearish = (
            previous_type == SwingType.HIGH
            and current_type == SwingType.LOW
        )

        return bullish or bearish

    # =====================================================
    # Fibonacci Levels
    # =====================================================

    def _calculate_levels(
        self,
        swing_low: float,
        swing_high: float,
        direction: FibonacciDirection,
    ) -> dict:

        price_range = swing_high - swing_low

        if price_range <= 0:
            raise ValueError(
                "Invalid swing range."
            )

        if direction == FibonacciDirection.BULLISH:

            return {
                "23.6": swing_high - price_range * 0.236,
                "38.2": swing_high - price_range * 0.382,
                "50.0": swing_high - price_range * 0.500,
                "61.8": swing_high - price_range * 0.618,
                "78.6": swing_high - price_range * 0.786,
            }

        if direction == FibonacciDirection.BEARISH:

            return {
                "23.6": swing_low + price_range * 0.236,
                "38.2": swing_low + price_range * 0.382,
                "50.0": swing_low + price_range * 0.500,
                "61.8": swing_low + price_range * 0.618,
                "78.6": swing_low + price_range * 0.786,
            }

        raise ValueError(
            f"Unknown direction: {direction}"
        )

    # =====================================================
    # Golden Zone
    # =====================================================

    @staticmethod
    def _golden_zone(
        levels: dict,
    ) -> tuple[float, float]:

        upper = max(
            levels["38.2"],
            levels["61.8"],
        )

        lower = min(
            levels["38.2"],
            levels["61.8"],
        )

        return upper, lower

    def _is_inside_golden_zone(
        self,
        price: float,
        levels: dict,
    ) -> bool:

        upper, lower = self._golden_zone(levels)

        return lower <= price <= upper

    # =====================================================
    # Pullback Validation
    # =====================================================

    def _validate_pullback(
        self,
        df: pd.DataFrame,
        impulse: dict,
        levels: dict,
    ) -> bool:

        close = float(df.iloc[-1]["Close"])

        if not self._is_inside_golden_zone(
            close,
            levels,
        ):
            return False

        if impulse["direction"] == FibonacciDirection.BULLISH:
            return close > impulse["low"]

        return close < impulse["high"]

    # =====================================================
    # Result Builder
    # =====================================================

    def _build_result(
        self,
        impulse: dict,
        levels: dict,
        pullback_valid: bool,
    ) -> SwingFibonacci:

        upper, lower = self._golden_zone(levels)

        return SwingFibonacci(

            direction=impulse["direction"],

            swing_high=float(
                impulse["high"]
            ),

            swing_low=float(
                impulse["low"]
            ),

            range_points=abs(
                impulse["high"]
                - impulse["low"]
            ),

            fib_236=levels["23.6"],
            fib_382=levels["38.2"],
            fib_500=levels["50.0"],
            fib_618=levels["61.8"],
            fib_786=levels["78.6"],

            golden_upper=upper,
            golden_lower=lower,

            pullback_valid=pullback_valid,
        )