# ============================================================
# FALCON Trading System
# File: core/models.py
#
# Description:
# Core dataclasses shared by every engine.
# These models are intentionally independent of any broker API.
#
# Author : OpenAI + Amitabh Kumar
# ============================================================

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional, List

from core.enums import (
    Trend,
    Bias,
    Strength,
    SwingType,
    StructureType,
    BreakType,
    LiquidityType,
    FVGType,
    FVGStatus,
    OrderBlockType,
    OrderBlockStatus,
    PriceZone,
    SignalType,
    EntryQuality,
    OrderSide,
    OrderStatus,
    PositionStatus,
    TradeResult,
)


# ============================================================
# CANDLE
# ============================================================

@dataclass(slots=True)
class Candle:
    """
    Standard OHLCV candle.
    """

    timestamp: datetime

    open: float
    high: float
    low: float
    close: float

    volume: float = 0.0


# ============================================================
# SWING
# ============================================================

@dataclass(slots=True)
class SwingPoint:
    """
    Swing High / Swing Low
    """

    index: int

    timestamp: datetime

    price: float

    swing_type: SwingType

    confirmed: bool = False


# ============================================================
# MARKET STRUCTURE
# ============================================================

@dataclass(slots=True)
class StructurePoint:
    """
    HH / HL / LH / LL
    """

    swing: SwingPoint

    structure: StructureType


@dataclass(slots=True)
class StructureBreak:
    """
    BOS / CHOCH
    """

    break_type: BreakType

    timestamp: datetime

    price: float

    bullish: bool


# ============================================================
# MARKET CONTEXT
# ============================================================

@dataclass(slots=True)
class MarketContext:
    """
    High level market state.
    """

    trend: Trend = Trend.RANGE

    bias: Bias = Bias.NEUTRAL

    strength: Strength = Strength.NORMAL


# ============================================================
# LIQUIDITY
# ============================================================

@dataclass(slots=True)
class LiquidityZone:
    """
    Liquidity area.
    """

    liquidity_type: LiquidityType

    high: float

    low: float

    active: bool = True


# ============================================================
# FAIR VALUE GAP
# ============================================================

@dataclass(slots=True)
class FairValueGap:
    """
    Fair Value Gap.
    """

    gap_type: FVGType

    upper: float

    lower: float

    created_at: datetime

    status: FVGStatus = FVGStatus.OPEN


# ============================================================
# ORDER BLOCK
# ============================================================

@dataclass(slots=True)
class OrderBlock:
    """
    Institutional Order Block.
    """

    block_type: OrderBlockType

    high: float

    low: float

    created_at: datetime

    status: OrderBlockStatus = OrderBlockStatus.ACTIVE


# ============================================================
# PREMIUM / DISCOUNT
# ============================================================

@dataclass(slots=True)
class PriceLocation:
    """
    Premium / Discount location.
    """

    zone: PriceZone

    equilibrium: float


# ============================================================
# ENTRY
# ============================================================

@dataclass(slots=True)
class TradeSignal:
    """
    Signal generated by Entry Engine.
    """

    signal: SignalType

    confidence: EntryQuality

    price: float

    stop_loss: float

    target: float

    timestamp: datetime

    reason: str = ""


# ============================================================
# ORDER
# ============================================================

@dataclass(slots=True)
class Order:
    """
    Broker order abstraction.
    """

    symbol: str

    side: OrderSide

    quantity: int

    entry: float

    stop_loss: float

    target: float

    status: OrderStatus = OrderStatus.CREATED


# ============================================================
# POSITION
# ============================================================

@dataclass(slots=True)
class Position:
    """
    Active position.
    """

    order: Order

    opened_at: datetime

    status: PositionStatus = PositionStatus.OPEN

    pnl: float = 0.0


# ============================================================
# TRADE
# ============================================================

@dataclass(slots=True)
class Trade:
    """
    Completed trade.
    """

    symbol: str

    side: OrderSide

    entry: float

    exit: float

    quantity: int

    opened_at: datetime

    closed_at: datetime

    pnl: float

    result: TradeResult


# ============================================================
# ENGINE RESULT
# ============================================================

@dataclass(slots=True)
class EngineResult:
    """
    Standard output of every engine.
    """

    success: bool

    message: str = ""

    data: Optional[object] = None


# ============================================================
# FALCON STATE
# ============================================================

@dataclass(slots=True)
class FalconState:
    """
    Shared runtime state.

    Every engine can update this object.
    """

    candles: List[Candle] = field(default_factory=list)

    swings: List[SwingPoint] = field(default_factory=list)

    structures: List[StructurePoint] = field(default_factory=list)

    liquidity: List[LiquidityZone] = field(default_factory=list)

    fvgs: List[FairValueGap] = field(default_factory=list)

    order_blocks: List[OrderBlock] = field(default_factory=list)

    context: MarketContext = field(default_factory=MarketContext)

    signal: Optional[TradeSignal] = None

    position: Optional[Position] = None