"""
=========================================================
PROJECT FALCON
Backtest Models
=========================================================

Models used exclusively by the Backtesting module.
"""

from dataclasses import dataclass


@dataclass(slots=True)
class BacktestOrder:
    """
    Order generated by StrategyRunner and consumed by
    BacktestTradeEngine.

    This class intentionally contains only the fields
    required for historical execution.
    """

    side: str
    entry: float
    stop_loss: float
    target: float

    confidence: float = 0.0

    risk_reward: float = 0.0