"""
=========================================================
PROJECT FALCON
Exit Decision Model
Version : 1.0
=========================================================

Represents the exit decision generated by the
ExitEngine.

The ExitEngine NEVER modifies a TradeDecision.
Instead, it evaluates the current trade and
returns an ExitDecision.

The TradeManager consumes this decision and
updates the TradeDecision accordingly.

This model contains ONLY exit decision state.
No business logic belongs here.
=========================================================
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from typing import Any

from models.enums import ExitReason


@dataclass(slots=True)
class ExitDecision:
    """
    Exit decision produced by ExitEngine.

    Produced by:
        ExitEngine

    Consumed by:
        TradeManager
    """

    # =====================================================
    # Decision
    # =====================================================

    should_exit: bool = False

    # =====================================================
    # Exit Details
    # =====================================================

    exit_reason: ExitReason = ExitReason.NONE
    exit_price: float = 0.0
    exit_time: datetime | None = None

    # =====================================================
    # Optional Information
    # =====================================================

    message: str = ""
    metadata: dict[str, Any] = field(default_factory=dict)