"""
=========================================================
Project FALCON
Structure Model
Version : 2.0
=========================================================
"""

from dataclasses import dataclass
from typing import Optional

import pandas as pd

from models.enums import StructureEvent, Direction


@dataclass(slots=True)
class StructurePoint:
    """
    Represents a confirmed market structure event.
    Generated by the Structure Engine after analysing swings.
    """

    # Candle index
    index: int

    # Candle timestamp
    datetime: Optional[pd.Timestamp]

    # BOS / CHOCH / NONE
    event: StructureEvent

    # Bullish / Bearish
    direction: Direction

    # Break price
    price: float

    # Broken swing index
    swing_index: Optional[int] = None

    # Whether the structure remains valid
    valid: bool = True

    def is_bullish(self) -> bool:
        return self.direction == Direction.LONG

    def is_bearish(self) -> bool:
        return self.direction == Direction.SHORT

    def __str__(self) -> str:
        return (
            f"[{self.index}] "
            f"{self.event.name} "
            f"{self.direction.name} "
            f"{self.price:.2f}"
        )