"""
=========================================================
PROJECT FALCON
Trade Setup Model
Version : 2.1
=========================================================

Represents a validated trading opportunity generated by
the Analysis Layer.

This model contains ONLY market analysis.

No confluence evaluation.
No confidence scoring.
No execution information.
"""

from dataclasses import dataclass, field
from typing import List

from models.enums import (
    Trend,
    Bias,
    Strength,
    Structure,
    Direction,
)


@dataclass(slots=True)
class TradeSetup:
    """
    Complete market analysis snapshot produced by the
    Analysis Layer.

    This model is the sole input to the Confluence Engine.
    """

    # =====================================================
    # Market Context
    # =====================================================

    trend: Trend = Trend.UNKNOWN

    bias: Bias = Bias.NEUTRAL

    strength: Strength = Strength.NORMAL

    structure: Structure = Structure.RANGE

    # =====================================================
    # Moving Averages
    # =====================================================

    ema_fast: float = 0.0

    ema_slow: float = 0.0

    ema_alignment: bool = False

    # =====================================================
    # Indicators
    # =====================================================

    rsi: float = 50.0

    adx: float = 0.0

    atr: float = 0.0

    high_volatility: bool = False

    

    # =====================================================
    # Smart Money Concepts
    # =====================================================

    liquidity: bool = False

    fibonacci: bool = False

    golden_zone: bool = False

    

    

    equal_highs: bool = False

    equal_lows: bool = False

    
    

    # =====================================================
    # Expected Trade Direction
    # =====================================================

    direction: Direction = Direction.NONE

    # =====================================================
    # Diagnostics
    # =====================================================

    reasons: List[str] = field(default_factory=list)

    # =====================================================
    # Validation
    # =====================================================

    valid: bool = False

    # =====================================================
    # Execution Inputs
    # =====================================================

    swing_high: float = 0.0

    swing_low: float = 0.0

    golden_zone_low: float = 0.0

    golden_zone_high: float = 0.0
    current_price: float = 0.0