"""
=========================================================
PROJECT FALCON
Trade Setup Model
Version : 2.0
=========================================================

Represents a validated trading opportunity generated by
the analysis engines.

This model contains ONLY market analysis.

No execution information should be stored here.
"""

from dataclasses import dataclass, field
from typing import List

from models.enums import (
    Trend,
    Bias,
    Strength,
    Structure,
    Direction,
)


@dataclass(slots=True)
class TradeSetup:
    """
    Market analysis produced before the Strategy Engine
    decides whether to enter a trade.
    """

    # =====================================================
    # Market Context
    # =====================================================

    trend: Trend = Trend.RANGE

    bias: Bias = Bias.NEUTRAL

    strength: Strength = Strength.NORMAL

    structure: Structure = Structure.RANGE

    # =====================================================
    # Moving Averages
    # =====================================================

    ema_fast: float = 0.0

    ema_slow: float = 0.0

    ema_alignment: bool = False

    # =====================================================
    # Indicators
    # =====================================================

    rsi: float = 50.0

    adx: float = 0.0

    atr: float = 0.0

    volume: float = 0.0

    # =====================================================
    # Smart Money Concepts
    # =====================================================

    liquidity: bool = False

    fibonacci: bool = False

    golden_zone: bool = False

    bos: bool = False

    choch: bool = False

    equal_highs: bool = False

    equal_lows: bool = False

    order_block: bool = False

    fair_value_gap: bool = False

    # =====================================================
    # Expected Direction
    # =====================================================

    direction: Direction = Direction.NONE

    # =====================================================
    # Quality Assessment
    # =====================================================

    confidence: float = 0.0

    confluence: float = 0.0

    # =====================================================
    # Diagnostics
    # =====================================================

    reasons: List[str] = field(default_factory=list)

    # =====================================================
    # Validation
    # =====================================================

    valid: bool = False